
Vagrant.configure(2) do |config|
  
 config.vm.define "JenkinsMaster", primary: true do |h|
    h.vm.box = "centos/7"
    h.vm.network "private_network", ip: "192.168.8.21"
	h.vm.hostname = 'JenkinsMaster'
    h.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1536"]
    end
  end

 config.vm.define "JenkinsNode1" do |h|
    h.vm.box = "centos/7"
    h.vm.network "private_network", ip: "192.168.8.22"
    h.vm.hostname = 'JenkinsNode1'
	h.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
  config.vm.define "JenkinsNode2" do |h|
    h.vm.box = "ubuntu/trusty64"
    h.vm.network "private_network", ip: "192.168.8.23"
    h.vm.hostname = 'JenkinsNode2'
	h.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end
 end 
 end 