
Vagrant.configure(2) do |config|
  
 config.vm.define "DockerRHELEE", primary: true do |h|
    h.vm.box = "generic/rhel8"
    h.vm.network "private_network", ip: "192.168.8.39"
	h.vm.hostname = 'DockerRHELEE'
    h.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1536"]
    end
  end

 config.vm.define "DockerC" do |h|
    h.vm.box = "centos/7"
    h.vm.network "private_network", ip: "192.168.8.38"
    h.vm.hostname = 'DockerNode1'
	h.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
  config.vm.define "DockerU" do |h|
    h.vm.box = "ubuntu/trusty64"
    h.vm.network "private_network", ip: "192.168.8.37"
    h.vm.hostname = 'DockerNode2'
	h.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end
 end 
 end 
