
Vagrant.configure(2) do |config|
  
 config.vm.define "KubeMaster", primary: true do |h|
    h.vm.box = "ubuntu/xenial64"
    h.vm.network "private_network", ip: "192.168.8.29"
	h.vm.hostname = 'KubeMaster'
    h.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end

 config.vm.define "KubeNode1" do |h|
    h.vm.box = "ubuntu/xenial64"
    h.vm.network "private_network", ip: "192.168.8.28"
    h.vm.hostname = 'KubeNode1'
	h.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1536"]
    end
  end
  config.vm.define "KubeNode2" do |h|
    h.vm.box = "ubuntu/xenial64"
    h.vm.network "private_network", ip: "192.168.8.27"
    h.vm.hostname = 'KubeNode2'
	h.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1536"]
  end
 end 
  config.vm.define "KubeNode3" do |h|
    h.vm.box = "ubuntu/xenial64"
    h.vm.network "private_network", ip: "192.168.8.26"
    h.vm.hostname = 'KubeNode3'
	h.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1536"]
  end
 end
 end 