# -*- mode: ruby -*-
# vi: set ft=ruby :

# README
#
# Getting Started:
# 1. vagrant plugin install vagrant-hostmanager
# 2. vagrant up
# 8. vagrant ssh
#
# This should put you at the control host
#  with access, by name, to other vms
Vagrant.configure(2) do |config|
  #config.hostmanager.enabled = true


  config.vm.define "JenkinsUbuntu", primary: true do |h|
    h.vm.box = "ubuntu/xenial64"
    h.vm.network "private_network", ip: "192.168.8.10"
    h.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "2048"]
      end
    h.vm.hostname = 'JenkinsUbuntu'
  end

  config.vm.define "JenkinsCentOS" do |h|
    h.vm.box = "centos/7"
    h.vm.network "private_network", ip: "192.168.8.11"
	h.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "2048"]
      end
    h.vm.hostname = 'JenkinsCentOS'
  end
  end