
Vagrant.configure(2) do |config|
  
	config.vm.define "AnsibleMaster", primary: true do |h|
    h.vm.box = "centos/7"
    h.vm.network "private_network", ip: "192.168.8.98"
	h.vm.hostname = 'AnsibleMaster'
    h.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end

  config.vm.define "AnsibleNode1" do |h|
    h.vm.box = "centos/7"
    h.vm.network "private_network", ip: "192.168.8.99"
    h.vm.hostname = 'AnsibleNode1'
	h.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
  end